import React from 'react';
import { Grid, InputBase, List, makeStyles, Paper, Typography } from '@material-ui/core';
import DashboardIcon from '@material-ui/icons/Dashboard';
import FormatShapesIcon from '@material-ui/icons/FormatShapes';
import PaletteIcon from '@material-ui/icons/Palette';
import Icon from '@material-ui/core/Icon';
import FontDownloadOutlinedIcon from '@material-ui/icons/FontDownloadOutlined';
import SearchIcon from '@material-ui/icons/Search';
import FontPicker from "../../components/FontPicker";
import Controls from '../../components/controls/Controls';




const useStyles = makeStyles(theme =>({
    noticeContent:{
      margin:theme.spacing(5),
      marginTop: theme.spacing(.5),
      marginBottom: theme.spacing(0),
      padding: theme.spacing(2),
      backgroundColor:'#fdfdfd',
      boxShadow:'1px 1px 3px #ccc',
      border:'solid 1px #0EE5A3',
    },
    wizardTitle:{
        margin:`${theme.spacing(2)}px ${theme.spacing(5)}px`,
        color:theme.palette.secondary.main,
        fontWeight:'600',
    },
    wizardItem:{
        display: 'flex',
        '& .MuiTypography-root':{
            marginLeft:theme.spacing(.5)
        }
    },
    iconBlock:{
        float:'left',
        margin:theme.spacing(.5),
        '&:hover':{
            backgroundColor:theme.palette.secondary.main,
        }
    },
    searchInput:{
        opacity:'0.8',
        padding:`3px ${theme.spacing(1)}px`,
        fontSize:'0.8rem',
        width:'100%',
        '&:hover':{
            backgroundColor:'#eee'
        },
        '& .MuiSvgIcon-root':{
            marginRight:theme.spacing(1)
        }
    },
    fontPicker:{
        '& #font-picker':{
            backgroundColor:'red'
        }
    },
    titles:{
        margin:theme.spacing(.5),
        width:'90%',
    }
}));

const menuItems = [{id:"ac_unit",label:"Ac Unit"},
{id:"access_alarm",label:"Access Alarm"},
{id:"access_alarms",label:"Access Alarms"},
{id:"access_time",label:"Access Time"},
{id:"accessibility",label:"Accessibility"},
{id:"accessibility_new",label:"Accessibility New"},
{id:"accessible",label:"Accessible"},
{id:"accessible_forward",label:"Accessible Forward"},
{id:"account_balance",label:"Account Balance"},
{id:"account_balance_wallet",label:"Account Balance Wallet"},
{id:"account_box",label:"Account Box"},
{id:"account_circle",label:"Account Circle"},
{id:"account_tree",label:"Account Tree"},
{id:"adb",label:"Adb"},
{id:"add",label:"Add"},
{id:"add_photo",label:"Add Photo"},
{id:"add_alarm",label:"Add Alarm"},
{id:"add_alert",label:"Add Alert"},
{id:"add_box",label:"Add Box"},
{id:"add_circle",label:"Add Circle"},
{id:"add_circle_outline",label:"Add Circle Outline"},
{id:"add_comment",label:"Add Comment"},
{id:"add_ic_call",label:"Add Ic Call"},
{id:"add_location",label:"Add Location"},
{id:"add_photo_alternate",label:"Add Photo Alternate"},
{id:"add_shopping_cart",label:"Add Shopping Cart"},
{id:"add_to_home_screen",label:"Add To Home Screen"},
{id:"add_to_photos",label:"Add To Photos"},
{id:"add_to_queue",label:"Add To Queue"},
{id:"adjust",label:"Adjust"},
{id:"airline_seat_flat",label:"Airline Seat Flat"},
{id:"airline_seat_flat_angled",label:"Airline Seat Flat Angled"},
{id:"airline_seat_individual_suite",label:"Airline Seat Individual Suite"},
{id:"airline_seat_legroom_extra",label:"Airline Seat Legroom Extra"},
{id:"airline_seat_legroom_normal",label:"Airline Seat Legroom Normal"},
{id:"airline_seat_legroom_reduced",label:"Airline Seat Legroom Reduced"},
{id:"airline_seat_recline_extra",label:"Airline Seat Recline Extra"},
{id:"airline_seat_recline_normal",label:"Airline Seat Recline Normal"},
{id:"airplanemode_active",label:"Airplanemode Active"},
{id:"airplanemode_inactive",label:"Airplanemode Inactive"},
{id:"airplay",label:"Airplay"},
{id:"airport_shuttle",label:"Airport Shuttle"},
{id:"alarm",label:"Alarm"},
{id:"alarm_add",label:"Alarm Add"},
{id:"alarm_off",label:"Alarm Off"},
{id:"alarm_on",label:"Alarm On"},
{id:"album",label:"Album"},
{id:"all_inbox",label:"All Inbox"},
{id:"all_inclusive",label:"All Inclusive"},
{id:"all_out",label:"All Out"},
{id:"alternate_email",label:"Alternate Email"},
{id:"amp_stories",label:"Amp Stories"},
{id:"android",label:"Android"},
{id:"announcement",label:"Announcement"},
{id:"apartment",label:"Apartment"},
{id:"apple",label:"Apple"},
{id:"apps",label:"Apps"},
{id:"archive",label:"Archive"},
{id:"arrow_back",label:"Arrow Back"},
{id:"arrow_back_ios",label:"Arrow Back Ios"},
{id:"arrow_downward",label:"Arrow Downward"},
{id:"arrow_drop_down",label:"Arrow Drop Down"},
{id:"arrow_drop_down_circle",label:"Arrow Drop Down Circle"},
{id:"arrow_drop_up",label:"Arrow Drop Up"},
{id:"arrow_forward",label:"Arrow Forward"},
{id:"arrow_forward_ios",label:"Arrow Forward Ios"},
{id:"arrow_left",label:"Arrow Left"},
{id:"arrow_right",label:"Arrow Right"},
{id:"arrow_right_alt",label:"Arrow Right Alt"},
{id:"arrow_upward",label:"Arrow Upward"},
{id:"art_track",label:"Art Track"},
{id:"aspect_ratio",label:"Aspect Ratio"},
{id:"assessment",label:"Assessment"},
{id:"assignment",label:"Assignment"},
{id:"assignment_ind",label:"Assignment Ind"},
{id:"assignment_late",label:"Assignment Late"},
{id:"assignment_return",label:"Assignment Return"},
{id:"assignment_returned",label:"Assignment Returned"},
{id:"assignment_turned_in",label:"Assignment Turned In"},
{id:"assistant",label:"Assistant"},
{id:"assistant_photo",label:"Assistant Photo"},
{id:"atm",label:"Atm"},
{id:"attach_file",label:"Attach File"},
{id:"attach_money",label:"Attach Money"},
{id:"attachment",label:"Attachment"},
{id:"audiotrack",label:"Audiotrack"},
{id:"autorenew",label:"Autorenew"},
{id:"av_timer",label:"Av Timer"},
{id:"backspace",label:"Backspace"},
{id:"backup",label:"Backup"},
{id:"ballot",label:"Ballot"},
{id:"bar_chart",label:"Bar Chart"},
{id:"bathtub",label:"Bathtub"},
{id:"battery",label:"Battery"},
{id:"battery",label:"Battery"},
{id:"battery",label:"Battery"},
{id:"battery",label:"Battery"},
{id:"battery",label:"Battery"},
{id:"battery",label:"Battery"},
{id:"battery_alert",label:"Battery Alert"},
{id:"battery_charging",label:"Battery Charging"},
{id:"battery_charging",label:"Battery Charging"},
{id:"battery_charging",label:"Battery Charging"},
{id:"battery_charging",label:"Battery Charging"},
{id:"battery_charging",label:"Battery Charging"},
{id:"battery_charging",label:"Battery Charging"},
{id:"battery_charging_full",label:"Battery Charging Full"},
{id:"battery_full",label:"Battery Full"},
{id:"battery_std",label:"Battery Std"},
{id:"battery_unknown",label:"Battery Unknown"},
{id:"beach_access",label:"Beach Access"},
{id:"beenhere",label:"Beenhere"},
{id:"block",label:"Block"},
{id:"bluetooth",label:"Bluetooth"},
{id:"bluetooth_audio",label:"Bluetooth Audio"},
{id:"bluetooth_connected",label:"Bluetooth Connected"},
{id:"bluetooth_disabled",label:"Bluetooth Disabled"},
{id:"bluetooth_searching",label:"Bluetooth Searching"},
{id:"blur_circular",label:"Blur Circular"},
{id:"blur_linear",label:"Blur Linear"},
{id:"blur_off",label:"Blur Off"},
{id:"blur_on",label:"Blur On"},
{id:"book",label:"Book"},
{id:"bookmark",label:"Bookmark"},
{id:"bookmark_border",label:"Bookmark Border"},
{id:"bookmarks",label:"Bookmarks"},
{id:"border_all",label:"Border All"},
{id:"border_bottom",label:"Border Bottom"},
{id:"border_clear",label:"Border Clear"},
{id:"border_color",label:"Border Color"},
{id:"border_horizontal",label:"Border Horizontal"},
{id:"border_inner",label:"Border Inner"},
{id:"border_left",label:"Border Left"},
{id:"border_outer",label:"Border Outer"},
{id:"border_right",label:"Border Right"},
{id:"border_style",label:"Border Style"},
{id:"border_top",label:"Border Top"},
{id:"border_vertical",label:"Border Vertical"},
{id:"branding_watermark",label:"Branding Watermark"},
{id:"brightness",label:"Brightness"},
{id:"brightness",label:"Brightness"},
{id:"brightness",label:"Brightness"},
{id:"brightness",label:"Brightness"},
{id:"brightness",label:"Brightness"},
{id:"brightness",label:"Brightness"},
{id:"brightness",label:"Brightness"},
{id:"brightness_auto",label:"Brightness Auto"},
{id:"brightness_high",label:"Brightness High"},
{id:"brightness_low",label:"Brightness Low"},
{id:"brightness_medium",label:"Brightness Medium"},
{id:"broken_image",label:"Broken Image"},
{id:"brush",label:"Brush"},
{id:"bubble_chart",label:"Bubble Chart"},
{id:"bug_report",label:"Bug Report"},
{id:"build",label:"Build"},
{id:"burst_mode",label:"Burst Mode"},
{id:"business",label:"Business"},
{id:"business_center",label:"Business Center"},
{id:"cached",label:"Cached"},
{id:"cake",label:"Cake"},
{id:"calendar_today",label:"Calendar Today"},
{id:"calendar_view_day",label:"Calendar View Day"},
{id:"call",label:"Call"},
{id:"call_end",label:"Call End"},
{id:"call_made",label:"Call Made"},
{id:"call_merge",label:"Call Merge"},
{id:"call_missed",label:"Call Missed"},
{id:"call_missed_outgoing",label:"Call Missed Outgoing"},
{id:"call_received",label:"Call Received"},
{id:"call_split",label:"Call Split"},
{id:"call_to_action",label:"Call To Action"},
{id:"camera",label:"Camera"},
{id:"camera_alt",label:"Camera Alt"},
{id:"camera_enhance",label:"Camera Enhance"},
{id:"camera_front",label:"Camera Front"},
{id:"camera_rear",label:"Camera Rear"},
{id:"camera_roll",label:"Camera Roll"},
{id:"cancel",label:"Cancel"},
{id:"cancel_presentation",label:"Cancel Presentation"},
{id:"cancel_schedule_send",label:"Cancel Schedule Send"},
{id:"card_giftcard",label:"Card Giftcard"},
{id:"card_membership",label:"Card Membership"},
{id:"card_travel",label:"Card Travel"},
{id:"casino",label:"Casino"},
{id:"cast",label:"Cast"},
{id:"cast_connected",label:"Cast Connected"},
{id:"cast_for_education",label:"Cast For Education"},
{id:"category",label:"Category"},
{id:"cell_wifi",label:"Cell Wifi"},
{id:"center_focus_strong",label:"Center Focus Strong"},
{id:"center_focus_weak",label:"Center Focus Weak"},
{id:"change_history",label:"Change History"},
{id:"chat",label:"Chat"},
{id:"chat_bubble",label:"Chat Bubble"},
{id:"chat_bubble_outline",label:"Chat Bubble Outline"},
{id:"check",label:"Check"},
{id:"check_box",label:"Check Box"},
{id:"check_box_outline_blank",label:"Check Box Outline Blank"},
{id:"check_circle",label:"Check Circle"},
{id:"check_circle_outline",label:"Check Circle Outline"},
{id:"chevron_left",label:"Chevron Left"},
{id:"chevron_right",label:"Chevron Right"},
{id:"child_care",label:"Child Care"},
{id:"child_friendly",label:"Child Friendly"},
{id:"chrome_reader_mode",label:"Chrome Reader Mode"},
{id:"class",label:"Class"},
{id:"clear",label:"Clear"},
{id:"clear_all",label:"Clear All"},
{id:"close",label:"Close"},
{id:"closed_caption",label:"Closed Caption"},
{id:"cloud",label:"Cloud"},
{id:"cloud_circle",label:"Cloud Circle"},
{id:"cloud_done",label:"Cloud Done"},
{id:"cloud_download",label:"Cloud Download"},
{id:"cloud_off",label:"Cloud Off"},
{id:"cloud_queue",label:"Cloud Queue"},
{id:"cloud_upload",label:"Cloud Upload"},
{id:"code",label:"Code"},
{id:"collections",label:"Collections"},
{id:"collections_bookmark",label:"Collections Bookmark"},
{id:"color_lens",label:"Color Lens"},
{id:"colorize",label:"Colorize"},
{id:"comment",label:"Comment"},
{id:"commute",label:"Commute"},
{id:"compare",label:"Compare"},
{id:"compare_arrows",label:"Compare Arrows"},
{id:"compass_calibration",label:"Compass Calibration"},
{id:"computer",label:"Computer"},
{id:"confirmation_number",label:"Confirmation Number"},
{id:"contact_mail",label:"Contact Mail"},
{id:"contact_phone",label:"Contact Phone"},
{id:"contact_support",label:"Contact Support"},
{id:"contactless",label:"Contactless"},
{id:"contacts",label:"Contacts"},
{id:"control_camera",label:"Control Camera"},
{id:"control_point",label:"Control Point"},
{id:"control_point_duplicate",label:"Control Point Duplicate"},
{id:"copyright",label:"Copyright"},
{id:"create",label:"Create"},
{id:"create_new_folder",label:"Create New Folder"},
{id:"credit_card",label:"Credit Card"},
{id:"crop",label:"Crop"},
{id:"crop",label:"Crop"},
{id:"crop",label:"Crop"},
{id:"crop",label:"Crop"},
{id:"crop",label:"Crop"},
{id:"crop_din",label:"Crop Din"},
{id:"crop_free",label:"Crop Free"},
{id:"crop_landscape",label:"Crop Landscape"},
{id:"crop_original",label:"Crop Original"},
{id:"crop_portrait",label:"Crop Portrait"},
{id:"crop_rotate",label:"Crop Rotate"},
{id:"crop_square",label:"Crop Square"},
{id:"dashboard",label:"Dashboard"},
{id:"data_usage",label:"Data Usage"},
{id:"date_range",label:"Date Range"},
{id:"deck",label:"Deck"},
{id:"dehaze",label:"Dehaze"},
{id:"delete",label:"Delete"},
{id:"delete_forever",label:"Delete Forever"},
{id:"delete_outline",label:"Delete Outline"},
{id:"delete_sweep",label:"Delete Sweep"},
{id:"departure_board",label:"Departure Board"},
{id:"description",label:"Description"},
{id:"desktop_access_disabled",label:"Desktop Access Disabled"},
{id:"desktop_mac",label:"Desktop Mac"},
{id:"desktop_windows",label:"Desktop Windows"},
{id:"details",label:"Details"},
{id:"developer_board",label:"Developer Board"},
{id:"developer_mode",label:"Developer Mode"},
{id:"device_hub",label:"Device Hub"},
{id:"device_unknown",label:"Device Unknown"},
{id:"devices",label:"Devices"},
{id:"devices_other",label:"Devices Other"},
{id:"dialer_sip",label:"Dialer Sip"},
{id:"dialpad",label:"Dialpad"},
{id:"directions",label:"Directions"},
{id:"directions_bike",label:"Directions Bike"},
{id:"directions_boat",label:"Directions Boat"},
{id:"directions_bus",label:"Directions Bus"},
{id:"directions_car",label:"Directions Car"},
{id:"directions_railway",label:"Directions Railway"},
{id:"directions_run",label:"Directions Run"},
{id:"directions_subway",label:"Directions Subway"},
{id:"directions_transit",label:"Directions Transit"},
{id:"directions_walk",label:"Directions Walk"},
{id:"disc_full",label:"Disc Full"},
{id:"dns",label:"Dns"},
{id:"dock",label:"Dock"},
{id:"domain",label:"Domain"},
{id:"domain_disabled",label:"Domain Disabled"},
{id:"done",label:"Done"},
{id:"done_all",label:"Done All"},
{id:"done_outline",label:"Done Outline"},
{id:"donut_large",label:"Donut Large"},
{id:"donut_small",label:"Donut Small"},
{id:"double_arrow",label:"Double Arrow"},
{id:"drafts",label:"Drafts"},
{id:"drag_handle",label:"Drag Handle"},
{id:"drag_indicator",label:"Drag Indicator"},
{id:"drive_eta",label:"Drive Eta"},
{id:"duo",label:"Duo"},
{id:"dvr",label:"Dvr"},
{id:"dynamic_feed",label:"Dynamic Feed"},
{id:"eco",label:"Eco"},
{id:"edit",label:"Edit"},
{id:"edit_attributes",label:"Edit Attributes"},
{id:"edit_location",label:"Edit Location"},
{id:"eject",label:"Eject"},
{id:"email",label:"Email"},
{id:"emoji_emotions",label:"Emoji Emotions"},
{id:"emoji_events",label:"Emoji Events"},
{id:"emoji_flags",label:"Emoji Flags"},
{id:"emoji_food_beverage",label:"Emoji Food Beverage"},
{id:"emoji_nature",label:"Emoji Nature"},
{id:"emoji_objects",label:"Emoji Objects"},
{id:"emoji_people",label:"Emoji People"},
{id:"emoji_symbols",label:"Emoji Symbols"},
{id:"emoji_transportation",label:"Emoji Transportation"},
{id:"enhanced_encryption",label:"Enhanced Encryption"},
{id:"equalizer",label:"Equalizer"},
{id:"error",label:"Error"},
{id:"error_outline",label:"Error Outline"},
{id:"euro",label:"Euro"},
{id:"euro_symbol",label:"Euro Symbol"},
{id:"ev_station",label:"Ev Station"},
{id:"event",label:"Event"},
{id:"event_available",label:"Event Available"},
{id:"event_busy",label:"Event Busy"},
{id:"event_note",label:"Event Note"},
{id:"event_seat",label:"Event Seat"},
{id:"exit_to_app",label:"Exit To App"},
{id:"expand_less",label:"Expand Less"},
{id:"expand_more",label:"Expand More"},
{id:"explicit",label:"Explicit"},
{id:"explore",label:"Explore"},
{id:"explore_off",label:"Explore Off"},
{id:"exposure",label:"Exposure"},
{id:"exposure_neg",label:"Exposure Neg"},
{id:"exposure_neg",label:"Exposure Neg"},
{id:"exposure_plus",label:"Exposure Plus"},
{id:"exposure_plus",label:"Exposure Plus"},
{id:"exposure_zero",label:"Exposure Zero"},
{id:"extension",label:"Extension"},
{id:"face",label:"Face"},
{id:"facebook",label:"Facebook"},
{id:"fast_forward",label:"Fast Forward"},
{id:"fast_rewind",label:"Fast Rewind"},
{id:"fastfood",label:"Fastfood"},
{id:"favorite",label:"Favorite"},
{id:"favorite_border",label:"Favorite Border"},
{id:"featured_play_list",label:"Featured Play List"},
{id:"featured_video",label:"Featured Video"},
{id:"feedback",label:"Feedback"},
{id:"fiber_dvr",label:"Fiber Dvr"},
{id:"fiber_manual_record",label:"Fiber Manual Record"},
{id:"fiber_new",label:"Fiber New"},
{id:"fiber_pin",label:"Fiber Pin"},
{id:"fiber_smart_record",label:"Fiber Smart Record"},
{id:"file_copy",label:"File Copy"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter",label:"Filter"},
{id:"filter_plus",label:"Filter Plus"},
{id:"filter_and",label:"Filter And"},
{id:"filter_center_focus",label:"Filter Center Focus"},
{id:"filter_drama",label:"Filter Drama"},
{id:"filter_frames",label:"Filter Frames"},
{id:"filter_hdr",label:"Filter Hdr"},
{id:"filter_list",label:"Filter List"},
{id:"filter_none",label:"Filter None"},
{id:"filter_tilt_shift",label:"Filter Tilt Shift"},
{id:"filter_vintage",label:"Filter Vintage"},
{id:"find_in_page",label:"Find In Page"},
{id:"find_replace",label:"Find Replace"},
{id:"fingerprint",label:"Fingerprint"},
{id:"fireplace",label:"Fireplace"},
{id:"first_page",label:"First Page"},
{id:"fitness_center",label:"Fitness Center"},
{id:"flag",label:"Flag"},
{id:"flare",label:"Flare"},
{id:"flash_auto",label:"Flash Auto"},
{id:"flash_off",label:"Flash Off"},
{id:"flash_on",label:"Flash On"},
{id:"flight",label:"Flight"},
{id:"flight_land",label:"Flight Land"},
{id:"flight_takeoff",label:"Flight Takeoff"},
{id:"flip",label:"Flip"},
{id:"flip_camera_android",label:"Flip Camera Android"},
{id:"flip_camera_ios",label:"Flip Camera Ios"},
{id:"flip_to_back",label:"Flip To Back"},
{id:"flip_to_front",label:"Flip To Front"},
{id:"folder",label:"Folder"},
{id:"folder_open",label:"Folder Open"},
{id:"folder_shared",label:"Folder Shared"},
{id:"folder_special",label:"Folder Special"},
{id:"font_download",label:"Font Download"},
{id:"format_align_center",label:"Format Align Center"},
{id:"format_align_justify",label:"Format Align Justify"},
{id:"format_align_left",label:"Format Align Left"},
{id:"format_align_right",label:"Format Align Right"},
{id:"format_bold",label:"Format Bold"},
{id:"format_clear",label:"Format Clear"},
{id:"format_color_fill",label:"Format Color Fill"},
{id:"format_color_reset",label:"Format Color Reset"},
{id:"format_color_text",label:"Format Color Text"},
{id:"format_indent_decrease",label:"Format Indent Decrease"},
{id:"format_indent_increase",label:"Format Indent Increase"},
{id:"format_italic",label:"Format Italic"},
{id:"format_line_spacing",label:"Format Line Spacing"},
{id:"format_list_bulleted",label:"Format List Bulleted"},
{id:"format_list_numbered",label:"Format List Numbered"},
{id:"format_list_numbered_rtl",label:"Format List Numbered Rtl"},
{id:"format_paint",label:"Format Paint"},
{id:"format_quote",label:"Format Quote"},
{id:"format_shapes",label:"Format Shapes"},
{id:"format_size",label:"Format Size"},
{id:"format_strikethrough",label:"Format Strikethrough"},
{id:"format_textdirection_to",label:"Format Textdirection To"},
{id:"format_textdirection_to",label:"Format Textdirection To"},
{id:"format_underlined",label:"Format Underlined"},
{id:"forum",label:"Forum"},
{id:"forward",label:"Forward"},
{id:"forward",label:"Forward"},
{id:"forward",label:"Forward"},
{id:"forward",label:"Forward"},
{id:"four",label:"Four"},
{id:"free_breakfast",label:"Free Breakfast"},
{id:"fullscreen",label:"Fullscreen"},
{id:"fullscreen_exit",label:"Fullscreen Exit"},
{id:"functions",label:"Functions"},
{id:"translate",label:"Translate"},
{id:"gamepad",label:"Gamepad"},
{id:"games",label:"Games"},
{id:"gavel",label:"Gavel"},
{id:"gesture",label:"Gesture"},
{id:"get_app",label:"Get App"},
{id:"gif",label:"Gif"},
{id:"git_hub",label:"Git Hub"},
{id:"golf_course",label:"Golf Course"},
{id:"gps_fixed",label:"Gps Fixed"},
{id:"gps_not_fixed",label:"Gps Not Fixed"},
{id:"gps_off",label:"Gps Off"},
{id:"grade",label:"Grade"},
{id:"gradient",label:"Gradient"},
{id:"grain",label:"Grain"},
{id:"graphic_eq",label:"Graphic Eq"},
{id:"grid_off",label:"Grid Off"},
{id:"grid_on",label:"Grid On"},
{id:"group",label:"Group"},
{id:"group_add",label:"Group Add"},
{id:"group_work",label:"Group Work"},
{id:"hd",label:"Hd"},
{id:"hdr_off",label:"Hdr Off"},
{id:"hdr_on",label:"Hdr On"},
{id:"hdr_strong",label:"Hdr Strong"},
{id:"hdr_weak",label:"Hdr Weak"},
{id:"headset",label:"Headset"},
{id:"headset_mic",label:"Headset Mic"},
{id:"healing",label:"Healing"},
{id:"hearing",label:"Hearing"},
{id:"height",label:"Height"},
{id:"help",label:"Help"},
{id:"help_outline",label:"Help Outline"},
{id:"high_quality",label:"High Quality"},
{id:"highlight",label:"Highlight"},
{id:"highlight_off",label:"Highlight Off"},
{id:"history",label:"History"},
{id:"home",label:"Home"},
{id:"home_work",label:"Home Work"},
{id:"horizontal_split",label:"Horizontal Split"},
{id:"hot_tub",label:"Hot Tub"},
{id:"hotel",label:"Hotel"},
{id:"hourglass_empty",label:"Hourglass Empty"},
{id:"hourglass_full",label:"Hourglass Full"},
{id:"house",label:"House"},
{id:"how_to_reg",label:"How To Reg"},
{id:"how_to_vote",label:"How To Vote"},
{id:"http",label:"Http"},
{id:"https",label:"Https"},
{id:"image",label:"Image"},
{id:"image_aspect_ratio",label:"Image Aspect Ratio"},
{id:"image_search",label:"Image Search"},
{id:"import_contacts",label:"Import Contacts"},
{id:"import_export",label:"Import Export"},
{id:"important_devices",label:"Important Devices"},
{id:"inbox",label:"Inbox"},
{id:"indeterminate_check_box",label:"Indeterminate Check Box"},
{id:"info",label:"Info"},
{id:"input",label:"Input"},
{id:"insert_chart",label:"Insert Chart"},
{id:"insert_comment",label:"Insert Comment"},
{id:"insert_drive_file",label:"Insert Drive File"},
{id:"insert_emoticon",label:"Insert Emoticon"},
{id:"insert_invitation",label:"Insert Invitation"},
{id:"insert_link",label:"Insert Link"},
{id:"insert_photo",label:"Insert Photo"},
{id:"instagram",label:"Instagram"},
{id:"invert_colors",label:"Invert Colors"},
{id:"invert_colors_off",label:"Invert Colors Off"},
{id:"iso",label:"Iso"},
{id:"keyboard",label:"Keyboard"},
{id:"keyboard_arrow_down",label:"Keyboard Arrow Down"},
{id:"keyboard_arrow_left",label:"Keyboard Arrow Left"},
{id:"keyboard_arrow_right",label:"Keyboard Arrow Right"},
{id:"keyboard_arrow_up",label:"Keyboard Arrow Up"},
{id:"keyboard_backspace",label:"Keyboard Backspace"},
{id:"keyboard_capslock",label:"Keyboard Capslock"},
{id:"keyboard_hide",label:"Keyboard Hide"},
{id:"keyboard_return",label:"Keyboard Return"},
{id:"keyboard_tab",label:"Keyboard Tab"},
{id:"keyboard_voice",label:"Keyboard Voice"},
{id:"king_bed",label:"King Bed"},
{id:"kitchen",label:"Kitchen"},
{id:"label",label:"Label"},
{id:"label_important",label:"Label Important"},
{id:"label_off",label:"Label Off"},
{id:"landscape",label:"Landscape"},
{id:"language",label:"Language"},
{id:"laptop",label:"Laptop"},
{id:"laptop_chromebook",label:"Laptop Chromebook"},
{id:"laptop_mac",label:"Laptop Mac"},
{id:"laptop_windows",label:"Laptop Windows"},
{id:"last_page",label:"Last Page"},
{id:"launch",label:"Launch"},
{id:"layers",label:"Layers"},
{id:"layers_clear",label:"Layers Clear"},
{id:"leak_add",label:"Leak Add"},
{id:"leak_remove",label:"Leak Remove"},
{id:"lens",label:"Lens"},
{id:"library_add",label:"Library Add"},
{id:"library_add_check",label:"Library Add Check"},
{id:"library_books",label:"Library Books"},
{id:"library_music",label:"Library Music"},
{id:"line_style",label:"Line Style"},
{id:"line_weight",label:"Line Weight"},
{id:"linear_scale",label:"Linear Scale"},
{id:"link",label:"Link"},
{id:"link_off",label:"Link Off"},
{id:"linked_camera",label:"Linked Camera"},
{id:"linked_in",label:"Linked In"},
{id:"list",label:"List"},
{id:"list_alt",label:"List Alt"},
{id:"live_help",label:"Live Help"},
{id:"live_tv",label:"Live Tv"},
{id:"local_activity",label:"Local Activity"},
{id:"local_airport",label:"Local Airport"},
{id:"local_atm",label:"Local Atm"},
{id:"local_bar",label:"Local Bar"},
{id:"local_cafe",label:"Local Cafe"},
{id:"local_car_wash",label:"Local Car Wash"},
{id:"local_convenience_store",label:"Local Convenience Store"},
{id:"local_dining",label:"Local Dining"},
{id:"local_drink",label:"Local Drink"},
{id:"local_florist",label:"Local Florist"},
{id:"local_gas_station",label:"Local Gas Station"},
{id:"local_grocery_store",label:"Local Grocery Store"},
{id:"local_hospital",label:"Local Hospital"},
{id:"local_hotel",label:"Local Hotel"},
{id:"local_laundry_service",label:"Local Laundry Service"},
{id:"local_library",label:"Local Library"},
{id:"local_mall",label:"Local Mall"},
{id:"local_movies",label:"Local Movies"},
{id:"local_offer",label:"Local Offer"},
{id:"local_parking",label:"Local Parking"},
{id:"local_pharmacy",label:"Local Pharmacy"},
{id:"local_phone",label:"Local Phone"},
{id:"local_pizza",label:"Local Pizza"},
{id:"local_play",label:"Local Play"},
{id:"local_post_office",label:"Local Post Office"},
{id:"local_printshop",label:"Local Printshop"},
{id:"local_see",label:"Local See"},
{id:"local_shipping",label:"Local Shipping"},
{id:"local_taxi",label:"Local Taxi"},
{id:"location_city",label:"Location City"},
{id:"location_disabled",label:"Location Disabled"},
{id:"location_off",label:"Location Off"},
{id:"location_on",label:"Location On"},
{id:"location_searching",label:"Location Searching"},
{id:"lock",label:"Lock"},
{id:"lock_open",label:"Lock Open"},
{id:"looks",label:"Looks"},
{id:"looks",label:"Looks"},
{id:"looks",label:"Looks"},
{id:"looks",label:"Looks"},
{id:"looks",label:"Looks"},
{id:"looks_one",label:"Looks One"},
{id:"looks_two",label:"Looks Two"},
{id:"loop",label:"Loop"},
{id:"loupe",label:"Loupe"},
{id:"low_priority",label:"Low Priority"},
{id:"loyalty",label:"Loyalty"},
{id:"mail",label:"Mail"},
{id:"mail_outline",label:"Mail Outline"},
{id:"map",label:"Map"},
{id:"markunread",label:"Markunread"},
{id:"markunread_mailbox",label:"Markunread Mailbox"},
{id:"maximize",label:"Maximize"},
{id:"meeting_room",label:"Meeting Room"},
{id:"memory",label:"Memory"},
{id:"menu",label:"Menu"},
{id:"menu_book",label:"Menu Book"},
{id:"menu_open",label:"Menu Open"},
{id:"merge_type",label:"Merge Type"},
{id:"message",label:"Message"},
{id:"mic",label:"Mic"},
{id:"mic_none",label:"Mic None"},
{id:"mic_off",label:"Mic Off"},
{id:"minimize",label:"Minimize"},
{id:"missed_video_call",label:"Missed Video Call"},
{id:"mms",label:"Mms"},
{id:"mobile_friendly",label:"Mobile Friendly"},
{id:"mobile_off",label:"Mobile Off"},
{id:"mobile_screen_share",label:"Mobile Screen Share"},
{id:"mode_comment",label:"Mode Comment"},
{id:"monetization_on",label:"Monetization On"},
{id:"money",label:"Money"},
{id:"money_off",label:"Money Off"},
{id:"monochrome_photos",label:"Monochrome Photos"},
{id:"mood",label:"Mood"},
{id:"mood_bad",label:"Mood Bad"},
{id:"more",label:"More"},
{id:"more_horiz",label:"More Horiz"},
{id:"more_vert",label:"More Vert"},
{id:"motorcycle",label:"Motorcycle"},
{id:"mouse",label:"Mouse"},
{id:"move_to_inbox",label:"Move To Inbox"},
{id:"movie",label:"Movie"},
{id:"movie_creation",label:"Movie Creation"},
{id:"movie_filter",label:"Movie Filter"},
{id:"multiline_chart",label:"Multiline Chart"},
{id:"museum",label:"Museum"},
{id:"music_note",label:"Music Note"},
{id:"music_off",label:"Music Off"},
{id:"music_video",label:"Music Video"},
{id:"my_location",label:"My Location"},
{id:"nature",label:"Nature"},
{id:"nature_people",label:"Nature People"},
{id:"navigate_before",label:"Navigate Before"},
{id:"navigate_next",label:"Navigate Next"},
{id:"navigation",label:"Navigation"},
{id:"near_me",label:"Near Me"},
{id:"network_cell",label:"Network Cell"},
{id:"network_check",label:"Network Check"},
{id:"network_locked",label:"Network Locked"},
{id:"network_wifi",label:"Network Wifi"},
{id:"new_releases",label:"New Releases"},
{id:"next_week",label:"Next Week"},
{id:"nfc",label:"Nfc"},
{id:"nights_stay",label:"Nights Stay"},
{id:"no_encryption",label:"No Encryption"},
{id:"no_meeting_room",label:"No Meeting Room"},
{id:"no_sim",label:"No Sim"},
{id:"not_interested",label:"Not Interested"},
{id:"not_listed_location",label:"Not Listed Location"},
{id:"note",label:"Note"},
{id:"note_add",label:"Note Add"},
{id:"notes",label:"Notes"},
{id:"notification_important",label:"Notification Important"},
{id:"notifications",label:"Notifications"},
{id:"notifications_active",label:"Notifications Active"},
{id:"notifications_none",label:"Notifications None"},
{id:"notifications_off",label:"Notifications Off"},
{id:"notifications_paused",label:"Notifications Paused"},
{id:"offline_bolt",label:"Offline Bolt"},
{id:"offline_pin",label:"Offline Pin"},
{id:"ondemand_video",label:"Ondemand Video"},
{id:"opacity",label:"Opacity"},
{id:"open_in_browser",label:"Open In Browser"},
{id:"open_in_new",label:"Open In New"},
{id:"open_with",label:"Open With"},
{id:"outdoor_grill",label:"Outdoor Grill"},
{id:"pages",label:"Pages"},
{id:"pageview",label:"Pageview"},
{id:"palette",label:"Palette"},
{id:"pan_tool",label:"Pan Tool"},
{id:"panorama",label:"Panorama"},
{id:"panorama_fish_eye",label:"Panorama Fish Eye"},
{id:"panorama_horizontal",label:"Panorama Horizontal"},
{id:"panorama_vertical",label:"Panorama Vertical"},
{id:"panorama_wide_angle",label:"Panorama Wide Angle"},
{id:"party_mode",label:"Party Mode"},
{id:"pause",label:"Pause"},
{id:"pause_circle_filled",label:"Pause Circle Filled"},
{id:"pause_circle_outline",label:"Pause Circle Outline"},
{id:"pause_presentation",label:"Pause Presentation"},
{id:"payment",label:"Payment"},
{id:"people",label:"People"},
{id:"people_alt",label:"People Alt"},
{id:"people_outline",label:"People Outline"},
{id:"perm_camera_mic",label:"Perm Camera Mic"},
{id:"perm_contact_calendar",label:"Perm Contact Calendar"},
{id:"perm_data_setting",label:"Perm Data Setting"},
{id:"perm_device_information",label:"Perm Device Information"},
{id:"perm_identity",label:"Perm Identity"},
{id:"perm_media",label:"Perm Media"},
{id:"perm_phone_msg",label:"Perm Phone Msg"},
{id:"perm_scan_wifi",label:"Perm Scan Wifi"},
{id:"person",label:"Person"},
{id:"person_add",label:"Person Add"},
{id:"person_add_disabled",label:"Person Add Disabled"},
{id:"person_outline",label:"Person Outline"},
{id:"person_pin",label:"Person Pin"},
{id:"person_pin_circle",label:"Person Pin Circle"},
{id:"personal_video",label:"Personal Video"},
{id:"pets",label:"Pets"},
{id:"phone",label:"Phone"},
{id:"phone_android",label:"Phone Android"},
{id:"phone_bluetooth_speaker",label:"Phone Bluetooth Speaker"},
{id:"phone_callback",label:"Phone Callback"},
{id:"phone_disabled",label:"Phone Disabled"},
{id:"phone_enabled",label:"Phone Enabled"},
{id:"phone_forwarded",label:"Phone Forwarded"},
{id:"phone_in_talk",label:"Phone In Talk"},
{id:"phone_iphone",label:"Phone Iphone"},
{id:"phone_locked",label:"Phone Locked"},
{id:"phone_missed",label:"Phone Missed"},
{id:"phone_paused",label:"Phone Paused"},
{id:"phonelink",label:"Phonelink"},
{id:"phonelink_erase",label:"Phonelink Erase"},
{id:"phonelink_lock",label:"Phonelink Lock"},
{id:"phonelink_off",label:"Phonelink Off"},
{id:"phonelink_ring",label:"Phonelink Ring"},
{id:"phonelink_setup",label:"Phonelink Setup"},
{id:"photo",label:"Photo"},
{id:"photo_album",label:"Photo Album"},
{id:"photo_camera",label:"Photo Camera"},
{id:"photo_filter",label:"Photo Filter"},
{id:"photo_library",label:"Photo Library"},
{id:"photo_size_select_actual",label:"Photo Size Select Actual"},
{id:"photo_size_select_large",label:"Photo Size Select Large"},
{id:"photo_size_select_small",label:"Photo Size Select Small"},
{id:"picture_as_pdf",label:"Picture As Pdf"},
{id:"picture_in_picture",label:"Picture In Picture"},
{id:"picture_in_picture_alt",label:"Picture In Picture Alt"},
{id:"pie_chart",label:"Pie Chart"},
{id:"pin_drop",label:"Pin Drop"},
{id:"pinterest",label:"Pinterest"},
{id:"place",label:"Place"},
{id:"play_arrow",label:"Play Arrow"},
{id:"play_circle_filled",label:"Play Circle Filled"},
{id:"play_circle_filled_white",label:"Play Circle Filled White"},
{id:"play_circle_outline",label:"Play Circle Outline"},
{id:"play_for_work",label:"Play For Work"},
{id:"playlist_add",label:"Playlist Add"},
{id:"playlist_add_check",label:"Playlist Add Check"},
{id:"playlist_play",label:"Playlist Play"},
{id:"plus_one",label:"Plus One"},
{id:"policy",label:"Policy"},
{id:"poll",label:"Poll"},
{id:"polymer",label:"Polymer"},
{id:"pool",label:"Pool"},
{id:"portable_wifi_off",label:"Portable Wifi Off"},
{id:"portrait",label:"Portrait"},
{id:"post_add",label:"Post Add"},
{id:"power",label:"Power"},
{id:"power_input",label:"Power Input"},
{id:"power_off",label:"Power Off"},
{id:"power_settings_new",label:"Power Settings New"},
{id:"pregnant_woman",label:"Pregnant Woman"},
{id:"present_to_all",label:"Present To All"},
{id:"print",label:"Print"},
{id:"print_disabled",label:"Print Disabled"},
{id:"priority_high",label:"Priority High"},
{id:"public",label:"Public"},
{id:"publish",label:"Publish"},
{id:"query_builder",label:"Query Builder"},
{id:"question_answer",label:"Question Answer"},
{id:"queue",label:"Queue"},
{id:"queue_music",label:"Queue Music"},
{id:"queue_play_next",label:"Queue Play Next"},
{id:"radio",label:"Radio"},
{id:"radio_button_checked",label:"Radio Button Checked"},
{id:"radio_button_unchecked",label:"Radio Button Unchecked"},
{id:"rate_review",label:"Rate Review"},
{id:"receipt",label:"Receipt"},
{id:"recent_actors",label:"Recent Actors"},
{id:"record_voice_over",label:"Record Voice Over"},
{id:"reddit",label:"Reddit"},
{id:"redeem",label:"Redeem"},
{id:"redo",label:"Redo"},
{id:"refresh",label:"Refresh"},
{id:"remove",label:"Remove"},
{id:"remove_circle",label:"Remove Circle"},
{id:"remove_circle_outline",label:"Remove Circle Outline"},
{id:"remove_from_queue",label:"Remove From Queue"},
{id:"remove_red_eye",label:"Remove Red Eye"},
{id:"remove_shopping_cart",label:"Remove Shopping Cart"},
{id:"reorder",label:"Reorder"},
{id:"repeat",label:"Repeat"},
{id:"repeat_one",label:"Repeat One"},
{id:"replay",label:"Replay"},
{id:"replay",label:"Replay"},
{id:"replay",label:"Replay"},
{id:"replay",label:"Replay"},
{id:"reply",label:"Reply"},
{id:"reply_all",label:"Reply All"},
{id:"report",label:"Report"},
{id:"report_off",label:"Report Off"},
{id:"report_problem",label:"Report Problem"},
{id:"restaurant",label:"Restaurant"},
{id:"restaurant_menu",label:"Restaurant Menu"},
{id:"restore",label:"Restore"},
{id:"restore_from_trash",label:"Restore From Trash"},
{id:"restore_page",label:"Restore Page"},
{id:"ring_volume",label:"Ring Volume"},
{id:"room",label:"Room"},
{id:"room_service",label:"Room Service"},
{id:"rotate_degrees_ccw",label:"Rotate Degrees Ccw"},
{id:"rotate_left",label:"Rotate Left"},
{id:"rotate_right",label:"Rotate Right"},
{id:"router",label:"Router"},
{id:"rowing",label:"Rowing"},
{id:"rss_feed",label:"Rss Feed"},
{id:"rv_hookup",label:"Rv Hookup"},
{id:"satellite",label:"Satellite"},
{id:"save",label:"Save"},
{id:"save_alt",label:"Save Alt"},
{id:"scanner",label:"Scanner"},
{id:"scatter_plot",label:"Scatter Plot"},
{id:"schedule",label:"Schedule"},
{id:"school",label:"School"},
{id:"score",label:"Score"},
{id:"screen_lock_landscape",label:"Screen Lock Landscape"},
{id:"screen_lock_portrait",label:"Screen Lock Portrait"},
{id:"screen_lock_rotation",label:"Screen Lock Rotation"},
{id:"screen_rotation",label:"Screen Rotation"},
{id:"screen_share",label:"Screen Share"},
{id:"sd_card",label:"Sd Card"},
{id:"sd_storage",label:"Sd Storage"},
{id:"search",label:"Search"},
{id:"security",label:"Security"},
{id:"select_all",label:"Select All"},
{id:"send",label:"Send"},
{id:"sentiment_dissatisfied",label:"Sentiment Dissatisfied"},
{id:"sentiment_satisfied",label:"Sentiment Satisfied"},
{id:"sentiment_satisfied_alt",label:"Sentiment Satisfied Alt"},
{id:"sentiment_very_dissatisfied",label:"Sentiment Very Dissatisfied"},
{id:"sentiment_very_satisfied",label:"Sentiment Very Satisfied"},
{id:"settings",label:"Settings"},
{id:"settings_applications",label:"Settings Applications"},
{id:"settings_backup_restore",label:"Settings Backup Restore"},
{id:"settings_bluetooth",label:"Settings Bluetooth"},
{id:"settings_brightness",label:"Settings Brightness"},
{id:"settings_cell",label:"Settings Cell"},
{id:"settings_ethernet",label:"Settings Ethernet"},
{id:"settings_input_antenna",label:"Settings Input Antenna"},
{id:"settings_input_component",label:"Settings Input Component"},
{id:"settings_input_composite",label:"Settings Input Composite"},
{id:"settings_input_hdmi",label:"Settings Input Hdmi"},
{id:"settings_input_svideo",label:"Settings Input Svideo"},
{id:"settings_overscan",label:"Settings Overscan"},
{id:"settings_phone",label:"Settings Phone"},
{id:"settings_power",label:"Settings Power"},
{id:"settings_remote",label:"Settings Remote"},
{id:"settings_system_daydream",label:"Settings System Daydream"},
{id:"settings_voice",label:"Settings Voice"},
{id:"share",label:"Share"},
{id:"shop",label:"Shop"},
{id:"shop_two",label:"Shop Two"},
{id:"shopping_basket",label:"Shopping Basket"},
{id:"shopping_cart",label:"Shopping Cart"},
{id:"short_text",label:"Short Text"},
{id:"show_chart",label:"Show Chart"},
{id:"shuffle",label:"Shuffle"},
{id:"shutter_speed",label:"Shutter Speed"},
{id:"signal_cellular_bar",label:"Signal Cellular Bar"},
{id:"signal_cellular_bar",label:"Signal Cellular Bar"},
{id:"signal_cellular_bar",label:"Signal Cellular Bar"},
{id:"signal_cellular_bar",label:"Signal Cellular Bar"},
{id:"signal_cellular_bar",label:"Signal Cellular Bar"},
{id:"signal_cellular_alt",label:"Signal Cellular Alt"},
{id:"signal_cellular_connected_no_internet_bar",label:"Signal Cellular Connected No Internet Bar"},
{id:"signal_cellular_connected_no_internet_bar",label:"Signal Cellular Connected No Internet Bar"},
{id:"signal_cellular_connected_no_internet_bar",label:"Signal Cellular Connected No Internet Bar"},
{id:"signal_cellular_connected_no_internet_bar",label:"Signal Cellular Connected No Internet Bar"},
{id:"signal_cellular_connected_no_internet_bar",label:"Signal Cellular Connected No Internet Bar"},
{id:"signal_cellular_no_sim",label:"Signal Cellular No Sim"},
{id:"signal_cellular_null",label:"Signal Cellular Null"},
{id:"signal_cellular_off",label:"Signal Cellular Off"},
{id:"signal_wifi_bar",label:"Signal Wifi Bar"},
{id:"signal_wifi_bar",label:"Signal Wifi Bar"},
{id:"signal_wifi_bar_lock",label:"Signal Wifi Bar Lock"},
{id:"signal_wifi_bar",label:"Signal Wifi Bar"},
{id:"signal_wifi_bar_lock",label:"Signal Wifi Bar Lock"},
{id:"signal_wifi_bar",label:"Signal Wifi Bar"},
{id:"signal_wifi_bar_lock",label:"Signal Wifi Bar Lock"},
{id:"signal_wifi_bar",label:"Signal Wifi Bar"},
{id:"signal_wifi_bar_lock",label:"Signal Wifi Bar Lock"},
{id:"signal_wifi_off",label:"Signal Wifi Off"},
{id:"sim_card",label:"Sim Card"},
{id:"single_bed",label:"Single Bed"},
{id:"skip_next",label:"Skip Next"},
{id:"skip_previous",label:"Skip Previous"},
{id:"slideshow",label:"Slideshow"},
{id:"slow_motion_video",label:"Slow Motion Video"},
{id:"smartphone",label:"Smartphone"},
{id:"smoke_free",label:"Smoke Free"},
{id:"smoking_rooms",label:"Smoking Rooms"},
{id:"sms",label:"Sms"},
{id:"sms_failed",label:"Sms Failed"},
{id:"snooze",label:"Snooze"},
{id:"sort",label:"Sort"},
{id:"sort_by_alpha",label:"Sort By Alpha"},
{id:"spa",label:"Spa"},
{id:"space_bar",label:"Space Bar"},
{id:"speaker",label:"Speaker"},
{id:"speaker_group",label:"Speaker Group"},
{id:"speaker_notes",label:"Speaker Notes"},
{id:"speaker_notes_off",label:"Speaker Notes Off"},
{id:"speaker_phone",label:"Speaker Phone"},
{id:"speed",label:"Speed"},
{id:"spellcheck",label:"Spellcheck"},
{id:"sports",label:"Sports"},
{id:"sports_baseball",label:"Sports Baseball"},
{id:"sports_basketball",label:"Sports Basketball"},
{id:"sports_cricket",label:"Sports Cricket"},
{id:"sports_esports",label:"Sports Esports"},
{id:"sports_football",label:"Sports Football"},
{id:"sports_golf",label:"Sports Golf"},
{id:"sports_handball",label:"Sports Handball"},
{id:"sports_hockey",label:"Sports Hockey"},
{id:"sports_kabaddi",label:"Sports Kabaddi"},
{id:"sports_mma",label:"Sports Mma"},
{id:"sports_motorsports",label:"Sports Motorsports"},
{id:"sports_rugby",label:"Sports Rugby"},
{id:"sports_soccer",label:"Sports Soccer"},
{id:"sports_tennis",label:"Sports Tennis"},
{id:"sports_volleyball",label:"Sports Volleyball"},
{id:"square_foot",label:"Square Foot"},
{id:"star",label:"Star"},
{id:"star_border",label:"Star Border"},
{id:"star_half",label:"Star Half"},
{id:"star_outline",label:"Star Outline"},
{id:"star_rate",label:"Star Rate"},
{id:"stars",label:"Stars"},
{id:"stay_current_landscape",label:"Stay Current Landscape"},
{id:"stay_current_portrait",label:"Stay Current Portrait"},
{id:"stay_primary_landscape",label:"Stay Primary Landscape"},
{id:"stay_primary_portrait",label:"Stay Primary Portrait"},
{id:"stop",label:"Stop"},
{id:"stop_screen_share",label:"Stop Screen Share"},
{id:"storage",label:"Storage"},
{id:"store",label:"Store"},
{id:"store_mall_directory",label:"Store Mall Directory"},
{id:"storefront",label:"Storefront"},
{id:"straighten",label:"Straighten"},
{id:"streetview",label:"Streetview"},
{id:"strikethrough",label:"Strikethrough"},
{id:"style",label:"Style"},
{id:"subdirectory_arrow_left",label:"Subdirectory Arrow Left"},
{id:"subdirectory_arrow_right",label:"Subdirectory Arrow Right"},
{id:"subject",label:"Subject"},
{id:"subscriptions",label:"Subscriptions"},
{id:"subtitles",label:"Subtitles"},
{id:"subway",label:"Subway"},
{id:"supervised_user_circle",label:"Supervised User Circle"},
{id:"supervisor_account",label:"Supervisor Account"},
{id:"surround_sound",label:"Surround Sound"},
{id:"swap_calls",label:"Swap Calls"},
{id:"swap_horiz",label:"Swap Horiz"},
{id:"swap_horizontal_circle",label:"Swap Horizontal Circle"},
{id:"swap_vert",label:"Swap Vert"},
{id:"swap_vertical_circle",label:"Swap Vertical Circle"},
{id:"switch_camera",label:"Switch Camera"},
{id:"switch_video",label:"Switch Video"},
{id:"sync",label:"Sync"},
{id:"sync_alt",label:"Sync Alt"},
{id:"sync_disabled",label:"Sync Disabled"},
{id:"sync_problem",label:"Sync Problem"},
{id:"system_update",label:"System Update"},
{id:"system_update_alt",label:"System Update Alt"},
{id:"tab",label:"Tab"},
{id:"tab_unselected",label:"Tab Unselected"},
{id:"table_chart",label:"Table Chart"},
{id:"tablet",label:"Tablet"},
{id:"tablet_android",label:"Tablet Android"},
{id:"tablet_mac",label:"Tablet Mac"},
{id:"tag_faces",label:"Tag Faces"},
{id:"tap_and_play",label:"Tap And Play"},
{id:"telegram",label:"Telegram"},
{id:"terrain",label:"Terrain"},
{id:"text_fields",label:"Text Fields"},
{id:"text_format",label:"Text Format"},
{id:"text_rotate_up",label:"Text Rotate Up"},
{id:"text_rotate_vertical",label:"Text Rotate Vertical"},
{id:"text_rotation_angledown",label:"Text Rotation Angledown"},
{id:"text_rotation_angleup",label:"Text Rotation Angleup"},
{id:"text_rotation_down",label:"Text Rotation Down"},
{id:"text_rotation_none",label:"Text Rotation None"},
{id:"textsms",label:"Textsms"},
{id:"texture",label:"Texture"},
{id:"theaters",label:"Theaters"},
{id:"three_rotation",label:"Three Rotation"},
{id:"three_sixty",label:"Three Sixty"},
{id:"thumb_down",label:"Thumb Down"},
{id:"thumb_down_alt",label:"Thumb Down Alt"},
{id:"thumb_up",label:"Thumb Up"},
{id:"thumb_up_alt",label:"Thumb Up Alt"},
{id:"thumbs_up_down",label:"Thumbs Up Down"},
{id:"time_to_leave",label:"Time To Leave"},
{id:"timelapse",label:"Timelapse"},
{id:"timeline",label:"Timeline"},
{id:"timer",label:"Timer"},
{id:"timer",label:"Timer"},
{id:"timer",label:"Timer"},
{id:"timer_off",label:"Timer Off"},
{id:"title",label:"Title"},
{id:"toc",label:"Toc"},
{id:"today",label:"Today"},
{id:"toggle_off",label:"Toggle Off"},
{id:"toggle_on",label:"Toggle On"},
{id:"toll",label:"Toll"},
{id:"tonality",label:"Tonality"},
{id:"touch_app",label:"Touch App"},
{id:"toys",label:"Toys"},
{id:"track_changes",label:"Track Changes"},
{id:"traffic",label:"Traffic"},
{id:"train",label:"Train"},
{id:"tram",label:"Tram"},
{id:"transfer_within_station",label:"Transfer Within Station"},
{id:"transform",label:"Transform"},
{id:"transit_enterexit",label:"Transit Enterexit"},
{id:"translate",label:"Translate"},
{id:"trending_down",label:"Trending Down"},
{id:"trending_flat",label:"Trending Flat"},
{id:"trending_up",label:"Trending Up"},
{id:"trip_origin",label:"Trip Origin"},
{id:"tune",label:"Tune"},
{id:"turned_in",label:"Turned In"},
{id:"turned_in_not",label:"Turned In Not"},
{id:"tv",label:"Tv"},
{id:"tv_off",label:"Tv Off"},
{id:"twitter",label:"Twitter"},
{id:"two_wheeler",label:"Two Wheeler"},
{id:"unarchive",label:"Unarchive"},
{id:"undo",label:"Undo"},
{id:"unfold_less",label:"Unfold Less"},
{id:"unfold_more",label:"Unfold More"},
{id:"unsubscribe",label:"Unsubscribe"},
{id:"update",label:"Update"},
{id:"usb",label:"Usb"},
{id:"verified_user",label:"Verified User"},
{id:"vertical_align_bottom",label:"Vertical Align Bottom"},
{id:"vertical_align_center",label:"Vertical Align Center"},
{id:"vertical_align_top",label:"Vertical Align Top"},
{id:"vertical_split",label:"Vertical Split"},
{id:"vibration",label:"Vibration"},
{id:"video_call",label:"Video Call"},
{id:"video_label",label:"Video Label"},
{id:"video_library",label:"Video Library"},
{id:"videocam",label:"Videocam"},
{id:"videocam_off",label:"Videocam Off"},
{id:"videogame_asset",label:"Videogame Asset"},
{id:"view_agenda",label:"View Agenda"},
{id:"view_array",label:"View Array"},
{id:"view_carousel",label:"View Carousel"},
{id:"view_column",label:"View Column"},
{id:"view_comfy",label:"View Comfy"},
{id:"view_compact",label:"View Compact"},
{id:"view_day",label:"View Day"},
{id:"view_headline",label:"View Headline"},
{id:"view_list",label:"View List"},
{id:"view_module",label:"View Module"},
{id:"view_quilt",label:"View Quilt"},
{id:"view_stream",label:"View Stream"},
{id:"view_week",label:"View Week"},
{id:"vignette",label:"Vignette"},
{id:"visibility",label:"Visibility"},
{id:"visibility_off",label:"Visibility Off"},
{id:"voice_chat",label:"Voice Chat"},
{id:"voice_over_off",label:"Voice Over Off"},
{id:"voicemail",label:"Voicemail"},
{id:"volume_down",label:"Volume Down"},
{id:"volume_mute",label:"Volume Mute"},
{id:"volume_off",label:"Volume Off"},
{id:"volume_up",label:"Volume Up"},
{id:"vpn_key",label:"Vpn Key"},
{id:"vpn_lock",label:"Vpn Lock"},
{id:"wallpaper",label:"Wallpaper"},
{id:"warning",label:"Warning"},
{id:"watch",label:"Watch"},
{id:"watch_later",label:"Watch Later"},
{id:"waves",label:"Waves"},
{id:"wb_auto",label:"Wb Auto"},
{id:"wb_cloudy",label:"Wb Cloudy"},
{id:"wb_incandescent",label:"Wb Incandescent"},
{id:"wb_iridescent",label:"Wb Iridescent"},
{id:"wb_sunny",label:"Wb Sunny"},
{id:"wc",label:"Wc"},
{id:"web",label:"Web"},
{id:"web_asset",label:"Web Asset"},
{id:"weekend",label:"Weekend"},
{id:"whats_app",label:"Whats App"},
{id:"whatshot",label:"Whatshot"},
{id:"where_to_vote",label:"Where To Vote"},
{id:"widgets",label:"Widgets"},
{id:"wifi",label:"Wifi"},
{id:"wifi_lock",label:"Wifi Lock"},
{id:"wifi_off",label:"Wifi Off"},
{id:"wifi_tethering",label:"Wifi Tethering"},
{id:"work",label:"Work"},
{id:"work_off",label:"Work Off"},
{id:"work_outline",label:"Work Outline"},
{id:"wrap_text",label:"Wrap Text"},
{id:"you_tube",label:"You Tube"},
{id:"youtube_searched_for",label:"Youtube Searched For"},
{id:"zoom_in",label:"Zoom In"},
{id:"zoom_out",label:"Zoom Out"},
{id:"zoom_out_map",label:"Zoom Out Map"}];

export default function Register() {

    const classes = useStyles();
    return (
        <>

        <div className={classes.wizardTitle}>
            <Typography
                variant="h6"
                component="div"
            >
                Let's get started
            </Typography>
        </div>

        <Paper className={classes.noticeContent}>
            <Grid container>
                <Grid item xs={12}>
                    <div className={classes.wizardItem}>
                        <FontDownloadOutlinedIcon />
                        <Typography variant="subtitle1" component="div">Enter Logo Texts</Typography>
                    </div>
                </Grid>
                <Grid item xs={12} md={6}>
                    <Controls.Input
                        className={classes.titles}
                        name="title"
                        label="Title"
                        //value={values.lastName}
                        //onChange={handleInputChange}
                        //error={errors.lastName}
                    />
                </Grid>
                <Grid item xs={12} md={6}>
                    <Controls.Input
                        className={classes.titles}
                        name="subTitle"
                        label="Sub Title"
                        //value={values.lastName}
                        //onChange={handleInputChange}
                        //error={errors.lastName}
                    />
                </Grid>
            </Grid>
        </Paper>

        <Paper className={classes.noticeContent}>
            <Grid container>
                <Grid item xs={12} style={{padding:'8px'}}>
                    <div className={classes.wizardItem}>
                        <DashboardIcon />
                        <Typography variant="subtitle1" component="div">Select Shapes</Typography>
                    </div>
                </Grid>
                <Grid item xs={12} md={8} style={{padding:'8px'}}>
                    <div>
                    <InputBase
                            placeholder="Search Shapes"
                            startAdornment={<SearchIcon />}
                            className={classes.searchInput}
                        />
                    <Paper style={{maxHeight:200, overflow:'auto', margin:'12px'}}>
                        <List>
                                {menuItems.map(({ id }) => {
                                    return (

                                        <Icon
                                            classes={{root:classes.iconBlock}}
                                            key={id}
                                            style={{fontSize:'2.5rem', color:'#444'}}
                                        >{id}</Icon>
                                    );
                                })}
                        </List>
                    </Paper>
                    </div>
                    
                </Grid>
                <Grid item xs={12} md={4} style={{padding:'8px'}}>
                    <Typography variant="subtitle2" component="div">Selected Shapes</Typography>
                    <div style={{margin:'8px', height:'200px', width:'100%'}}>
                    </div>
                </Grid>
            </Grid>
        </Paper> 


        <Paper className={classes.noticeContent}>
            <Grid container>
                <Grid item xs={12} md={8} style={{padding:'8px'}}>
                    <div className={classes.wizardItem}>
                        <FormatShapesIcon />
                        <Typography variant="subtitle1" component="div">Select Fonts</Typography>
                    </div>
                    <div>
                        <InputBase
                                placeholder="Search Fonts"
                                startAdornment={<SearchIcon />}
                                className={classes.searchInput}
                            />
                        <FontPicker />

                        <Controls.Button
                            text="+ Add Font"
                            color="secondary"
                        />
                    </div>
                </Grid>
                <Grid item xs={12} md={4} style={{padding:'8px'}}>
                    <Typography variant="subtitle2" component="div">Selected Fonts</Typography>
                    <div style={{margin:'8px', height:'200px', width:'100%'}}>
                    </div>
                </Grid>
            </Grid>
        </Paper>

        <Paper className={classes.noticeContent}>
            <Grid container>
                <Grid item xs={12}>
                    <div className={classes.wizardItem}>
                        <PaletteIcon />
                        <Typography variant="subtitle1" component="div">Select Colors</Typography>
                    </div>
                </Grid>
            </Grid>
        </Paper>

        <Paper className={classes.noticeContent}>
            <Grid container>
                <Grid item xs={12} style={{textAlign:'center'}}>
                    <Controls.Button
                        text="Generate my Logos"
                        color="primary"
                    />
                </Grid>
            </Grid>
        </Paper>

        </>
    )
}
